
/**
 * Created by marno on 2017/4/6
 * Function:图片管理类
 */
export default {
    icon: {
        logo: ()=>require('./images/logo.png'),
        alarm: ()=>require('./images/alarm.png'),
        back: ()=>require('./images/back.png'),
        backWhite: ()=>require('./images/backWhite.png'),
        dotMenu: ()=>require('./images/dotMenu.png'),
        search: ()=>require('./images/search.png'),
        close_wb: ()=>require('./images/close_wb.png'),
        noResult: ()=>require('./images/noResult.png'),
        serverError: ()=>require('./images/serverError.png'),
        plus: ()=>require('./images/plus.png'),
        lock: ()=>require('./images/lock.png'),
        next: ()=>require('./images/next.png'),
        upgradeHeader:()=>require('./images/upgradeHeader.png'),
        default: ()=>require('./images/default.png'),
        default_failed: ()=>require('./images/default_failed.png'),
        refresh: ()=>require('./images/refresh.png'),
        showInterest: ()=>require('./images/showInterest.png'),
        shortlisted: ()=>require('./images/shortlisted.png'),
        appointed: ()=>require('./images/appointed.png'),
        arrow_down: ()=>require('./images/arrow_down.png'),
        arrow_up: ()=>require('./images/arrow_up.png'),
        calendar: ()=>require('./images/calendar.png'),
        calendar2: ()=>require('./images/calendar2.png'),
        pdf: ()=>require('./images/pdf.png'),
        camera: ()=>require('./images/camera.png'),
        fixed: ()=>require('./images/fixed.png'),
        return: ()=>require('./images/return.png'),
        timeLine: ()=>require('./images/timeLine.png'),
        close_w: ()=>require('./images/close_white.png'),
        download: ()=>require('./images/download.png'),
        camera_select: ()=>require('./images/camera_select.png'),
        image_add: ()=>require('./images/image_add.png'),
        image_close: ()=>require('./images/image_close.png'),
        delete: ()=>require('./images/delete.png'),
        closeBlack: ()=>require('./images/close_black.png'),
        attachmentPdf: ()=>require('./images/attachmentPdf.png'),
        attachmentXls: ()=>require('./images/attachmentXls.png'),
        attachmentDoc: ()=>require('./images/attachmentDoc.png'),
        attachmentJpg: ()=>require('./images/attachmentJpg.png'),
        attachmentPng: ()=>require('./images/attachmentPng.png'),
        attachmentGif: ()=>require('./images/attachmentGif.png'),
        attachmentTiff: ()=>require('./images/attachmentTiff.png'),
        attachmentPpt: ()=>require('./images/attachmentPpt.png'),
        attachmentUnknown: ()=>require('./images/attachmentUnknown.png'),
        checkbox: ()=>require('./images/checkbox.png'),
        checkboxNormal: ()=>require('./images/checkboxNormal.png'),
        detailDelivery: ()=>require('./images/detailDelivery.png'),
        detailRecap: ()=>require('./images/detailRecap.png'),
        detailOffer: ()=>require('./images/detailOffer.png'),
        detailNo: ()=>require('./images/detailNo.png'),
        detailLift: ()=>require('./images/detailLift.png'),
        Close: ()=>require('./images/Close.png'),
        sent: ()=>require('./images/sent.png'),
    },
    tabBar: {
        ic_home:  ()=>require('./images/tabbar/home.png'),
        ic_tools:  ()=>require('./images/tabbar/tools.png'),
        ic_order:  ()=>require('./images/tabbar/rfq.png'),
        ic_search:  ()=>require('./images/tabbar/search.png'),
        ic_profile:  ()=>require('./images/tabbar/myMOL.png'),
        tab_cargo:  ()=>require('./images/tabbar/tab_cargo.png'),
        tab_me:  ()=>require('./images/tabbar/tab_me.png'),
        tab_home:  ()=>require('./images/tabbar/tab_home.png')
    },
    home: {
        home_bg:  ()=>require('./images/home/home_bg.png'),
        home_tab_bg:  ()=>require('./images/home/home_tab_bg.png'),
        home_tab_bg2:  ()=>require('./images/home/home_tab_bg2.png'),
        home_title_vessel:  ()=>require('./images/home/home_title_vessel.png'),
        home_vessel:  ()=>require('./images/home/home_vessel.png'),
        home_comingsoon:  ()=>require('./images/home/home_comingsoon.png'),
    },
    me: {
        Me_about_icon:  ()=>require('./images/me/Me_about_icon.png'),
        Me_language_icon:  ()=>require('./images/me/Me_language_icon.png'),
        Me_password_icon:  ()=>require('./images/me/Me_password_icon.png'),
        Me_Sigin_topbg:  ()=>require('./images/me/Me_Sigin_topbg.png'),
        Me_user_icon:  ()=>require('./images/me/Me_user_icon.png'),
        Me_login:  ()=>require('./images/me/Me_login.png'),
    },
    login: {
        login_bg:  ()=>require('./images/login/login_bg.png'),
        login_logo:  ()=>require('./images/login/login_logo.png'),
        login_Password:  ()=>require('./images/login/login_Password.png'),
        login_User:  ()=>require('./images/login/login_User.png'),
        login_Contact:  ()=>require('./images/login/login_Contact.png'),
    },
    vessels: {
        Anchor: ()=>require('./images/vessels/Anchor.png'),
        Cargo: ()=>require('./images/vessels/Cargo.png'),
        Fishing: ()=>require('./images/vessels/Fishing.png'),
        Other: ()=>require('./images/vessels/Other.png'),
        Passenger: ()=>require('./images/vessels/Passenger.png'),
        Pleasure_Craft: ()=>require('./images/vessels/Pleasure_Craft.png'),
        Sailing: ()=>require('./images/vessels/Sailing.png'),
        Tanker: ()=>require('./images/vessels/Tanker.png'),
        Tug: ()=>srequire('./images/vessels/Tug.png'),
    },
};
